## Standard Library
### Problem 1

In [2]:
# input a list of numbers by yourself
import numpy as np
input_list = []
n = int(input("How many numbers in your list? "))
for i in range(0,n):
    print("you will input",i+1,"th number:")
    ele = float(input())
    input_list.append(ele)
print('Minimum: %.2f' % min(input_list), 'Maximun: %.2f' % max(input_list), 'Mean: %.2f' % np.mean(input_list))

How many numbers in your list? 3
you will input 1 th number:
1
you will input 2 th number:
3
you will input 3 th number:
4
Minimum: 1.00 Maximun: 4.00 Mean: 2.67


### Problem 2

In [4]:
# Checking whether int is mutable
int_1 = 777
int_2 = int_1
int_2 = 888
if int_1 == int_2:
    print("int is mutable")
else:
    print("int is immutable")

# Checking whether str is mutable
str_1 = 'Python3.0'
str_2 = str_1
str_2 = 'Python2.0'
if str_1 == str_2:
    print("str is mutable")
else:
    print("str is immutable")

# Checking whether list is mutable
list_1 = [1,2,3,4,5]
list_2 = list_1
list_2[3] = 7
if list_1 == list_2:
    print("list is mutable")
else:
    print("list is immutable")

# Checking whether tuple is mutable
tuple_1 = [1, 2, 3, 'a', 'b', 'c']
tuple_2 = tuple_1
tuple_2 = [1, 2, 4, 'a', 'b', 'c']
if tuple_1 == tuple_2:
    print("tuple is mutable")
else:
    print("tuple is immutable")

# Checking whether set is mutable
set_1 = {1, 1, 2, 2, 3, 3}
set_2 = set_1
set_2 = {1, 1, 2, 2, 3, 4}
if set_1 == set_2:
    print("set is mutable")
else:
    print("set is immutable")

int is immutable
str is immutable
list is mutable
tuple is immutable
set is immutable


### Problem 3

In [1]:
import calculator as ca

# The function of calculating hypotenuse
def hypo_tri(x, y):
    x1 = x * x
    y1 = y * y
    z1 = ca.c_sum(x1, y1)
    z = ca.sqrt(z1)
    return z

hypo_tri(30, 40)

50.0

## Introduction to NumPy

### Problem 1

In [2]:
import numpy as np
A = np.array([[3, -1, 4], [1, 5, -9]])
B = np.array([[2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3]])
C = np.dot(A,B)
D = A @ B

if np.array_equal(C, D):
    print("C = D")
    print(C)
else:
    print("C != D")
    print("C is:", C, "D is:", D )

C = D
[[ 37  14 -32 -10]
 [-54  -7  58  65]]


### Problem 2

In [3]:
import numpy as np
def arr_func(A = np.array([[3, 1, 4], [1, 5, 9], [-5, 3, 1]])):
    u = (-1) * A * A * A + 9 * A * A - 15 * A
    return u
arr_func()

# The result shows that the component-wise calculation in the function can get the same result

array([[   9,   -7,   20],
       [  -7,   25, -135],
       [ 425,    9,   -7]])

### Problem 5

In [4]:
import numpy as np

# Define a function
def array_create(A0 = np.arange(6), A1 = np.ones((3, 3), dtype = np.int)):
    AT = np.reshape(A0, (3, 2))
    A = AT.T
    B1 = A1 * 3
    B = np.tril(B1)
    C1 = A1 * (-2)
    C2 = np.tril(C1)
    C = np.triu(C2)
    O3 = np.zeros((3, 3), dtype = np.int)
    O2 = np.zeros((2, 2), dtype = np.int)
    I3 = np.eye(3, dtype = np.int)
    O23 = np.zeros((2, 3), dtype = np.int)
    ROW1 = np.hstack((O3, A.T, I3))
    ROW2 = np.hstack((A, O2, O23))
    ROW3 = np.hstack((B, O23.T, C))
    Block = np.vstack((ROW1, ROW2, ROW3))
    return Block
array_create()

array([[ 0,  0,  0,  0,  1,  1,  0,  0],
       [ 0,  0,  0,  2,  3,  0,  1,  0],
       [ 0,  0,  0,  4,  5,  0,  0,  1],
       [ 0,  2,  4,  0,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0,  0],
       [ 3,  0,  0,  0,  0, -2,  0,  0],
       [ 3,  3,  0,  0,  0,  0, -2,  0],
       [ 3,  3,  3,  0,  0,  0,  0, -2]])

## Object Oriented Programming

### Problem 1

In [5]:
class Backpack(object):
    """ A Backpack V.1.1 object class. Has a name, a color, a max_size and
        a list of contents.
        
    Attributes: 
        name (str): the name of the backpack's owner.
        color (str): the color of the backpack.
        max_size (int): the size of the backpack. 
        contents (list): the contents of the backpack.
    """
    def __init__(self, name, color, max_size = 5):     # The contructor.

        self.name = name                    # Initialize some attributes.
        self.color = color
        self.max_size = max_size
        self.contents = []
        
    
    def put(self, item):
        """
        Add 'item' to the backpack's list of contents, 
        if current number of contents is less than max_size.
        """
        if len(self.contents) >= self.max_size:
            print("No Room!")
        else:
            self.contents.append(item)    
    
    def dump(self):
        """Dump all items in the backpack"""
        self.contents.clear()
     

### Problem 2

In [6]:
class Jetpack(Backpack):
    
    def __init__(self, name, color, max_size = 2, fuel = 10):
        Backpack.__init__(self, name, color, max_size)
        self.fuel = fuel
    
    def fly(self):
        fue_bur = int(input("How much fuel do you want to:"))
        if fue_bur >= self.fuel:
            print("Not enough fuel!")
        else:
            self.fuel -= fue_bur
            print("%s still has" % self.name, self.fuel, "fuel")
    
    def dump(self):
        self.contents.clear()
        self.fuel.clear()